export {
  ArrowRightIcon,
  ArrowUpRightIcon,
  BrainIcon,
  BugBeetleIcon,
  BuildingsIcon as BuildingIcon,
  ChatsCircleIcon,
  CheckCircleIcon as CheckIcon,
  CodeIcon,
  FacebookLogoIcon as FacebookIcon,
  FlowArrowIcon,
  GraduationCapIcon,
  GithubLogoIcon as GithubIcon,
  InstagramLogoIcon as InstagramIcon,
  ListIcon as MenuIcon,
  ListChecksIcon,
  LightbulbIcon,
  MagnifyingGlassIcon,
  PaperPlaneTiltIcon as SendIcon,
  PencilRulerIcon,
  StudentIcon,
  RocketLaunchIcon,
  SparkleIcon,
  TargetIcon,
  TiktokLogoIcon as MusicIcon,
  WhatsappLogoIcon as WhatsappIcon,
  XIcon as CloseIcon,
  EnvelopeIcon as EnvelopeIcon,
} from "@phosphor-icons/react/ssr";
